# Generated by Django 5.2.4 on 2025-07-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lavanderia", "0004_item_retornou_inventario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventario",
            name="quantidade",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="inventario",
            unique_together={("categoria", "tamanho")},
        ),
    ]
