# Generated by Django 5.2.4 on 2025-07-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lavanderia", "0005_alter_inventario_quantidade_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="OrdemServico",
        ),
    ]
