# Generated by Django 5.2.4 on 2025-07-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lavanderia", "0006_rename_item_ordemservico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemservico",
            name="status",
            field=models.CharField(
                choices=[
                    ("Sujo", "Sujo"),
                    ("Manchado", "Manchado"),
                    ("Lavando", "Lavando"),
                    ("Limpo", "Limpo"),
                    ("Retornou com mancha", "Retornou com mancha"),
                    ("Operação concluída", "Operação concluída"),
                ],
                max_length=50,
            ),
        ),
    ]
